### ISSUE TITLE
Copy button

### ISSUE THREAD

**Issue by evolution-ant** [wong2/chat-gpt-google-extension#115]
maybe it needs a copy button

**Comment by xihajun** [comment]
Do we need to update to the latest version to get the copy button?
<img width="447" alt="image" src="https://user-images.githubusercontent.com/25631641/209451627-a92a3fa3-2b97-43ac-93d7-f2d63e1a8b35.png">

Because currently, I cannot seems to find that. Also, if it is possible to have two options: 1. to copy the whole markdown text, 2. to copy the code block?
