### ISSUE TITLE
Analytics & Source code

### ISSUE THREAD

**Issue by TiesdeKok** [wong2/chat-gpt-google-extension#197]
Thanks for this great extension; I use it a lot!

Two related questions:

1.  #155 added analytics and tracking to the extension, but there is no discussion on what this is used for. The Chrome Web Store page also still indicates that the extension does not collect any user data, which does not seem accurate (anymore). What is the objective of the tracking, and who is that information shared with?

2. The version on the Chrome Web Store page (1.15.3) is two weeks ahead of the most recent source code on Github (1.14). Auditing the extension source code from the web store build is not possible due to the way the extension is built/minified. Keeping the web store version in sync with the Github source code would give some more peace of mind for those that prefer to install from source.

Thanks!

**Comment by ElectraPort** [comment]
+1 for item #1, I started looking into a feature request Thursday and immediately noticed this in analytics.ts, which includes an API key for an account at posthog:

```
import posthog from 'posthog-js'
import { getExtensionVersion } from './utils'

posthog.init('<key omitted>', {
  api_host: 'https://app.posthog.com',
  persistence: 'localStorage',
  autocapture: false,
  capture_pageview: false,
  disable_session_recording: true,
  property_blacklist: ['$current_url', '$pathname'],
  loaded: (pg) => {
    pg.people.set({ ext_version: getExtensionVersion() })
  },
})

export function captureEvent(event: string, properties?: object) {
  posthog.capture(event, properties)
}
```

and while I didn't have a chance to make this post before you, I'll thank you for doing it and specifically weigh in to wonder why an open source plugin is logging to a specific account on posthog, and who is viewing those reports?

**Comment by wong2** [comment]
Thanks for bringing this up, actually the Posthog analytics has been removed since v1.15.0, and I'll push the latest source code soon.

I added Posthog analytics to learn usage data, like how many times the ChatGPT card is displayed, and I've intentional collect minimal data, as you can see from the above code, I disabled all unnecessary data metrics from the posthog library.
However, since my extension has many users, the data points collected soon exceeded what's provided by Posthog's free plan, so I removed the analytics code in v1.15.0

**Comment by wong2** [comment]
I've deliberately stopped syncing code to this repo recently, because I found some extensions (to name one: <ChatGPT for search engines>) are copying my code and redistribute them. Yet, you're right that "Keeping the web store version in sync with the Github source code would give some more peace of mind". I'm still figuring this out!

**Comment by TiesdeKok** [comment]
Thanks for the quick follow-up! Sorry to hear people are redistributing your extension without properly adhering to the GNU-3 license; that sucks...

You making your work available open-source with a reasonable license inspired many others (including myself) to create derivative projects for other non-competing use cases. Which is the positive flip side and something we are all grateful for! 😃 

I will close the issue now because it has been answered.

**Comment by josStorer** [comment]
@wong2 

I installed "ChatGPT for search engines", and after briefly examining some of the source code, I think it may be using the code you distributed under GPL

For example, search background.js of that extension, and you can get

```javascript
if(e.type==="FEEDBACK"){let t=await ie();await Ie(t,e.data)}else e.type==="OPEN_OPTIONS_PAGE"&&B.default. runtime.openOptionsPage()
```

It comes from your commit f34b6cd0b8c1cc5f81a1f444ee83b694bb24e7ba

For strings like OPEN_OPTIONS_PAGE, the exact same name is used, there are also some other traces besides that 

Is it possible to report an infringement to the Chrome Store https://support.google.com/chrome_webstore/answer/7508032

By the way, I think you can pin this issue before new commits

**Comment by wong2** [comment]
Yeah I reported to Google, but they don't think it violates their policies
