### ISSUE TITLE
Non-flatpack Linux: This add-on is not available on your platform.

### ISSUE THREAD

**Issue by chapmanjacobd** [wong2/chat-gpt-google-extension#27]
On OpenSuSe Firefox I get the message "This add-on is not available on your platform." in Mozilla Addons.

Also, "Access your data for all websites" seems pretty aggressive. Think you could make it only use www.google.com and *.openai.com ?

**Comment by wong2** [comment]
Can you install other addons in the Mozilla Addons site?

**Comment by chapmanjacobd** [comment]
Yes. Also I checked my other computer running Fedora and I get the same message

**Comment by omergoktas** [comment]
I can use it in Flatpak version of Firefox on Linux without a problem. Just so you know.

**Comment by marauder37** [comment]
> Also, "Access your data for all websites" seems pretty aggressive. Think you could make it only use [www.google.com](http://www.google.com) and *.openai.com ?

Google has about 200 country-specific search domains. It's not possible to limit the manifest `matches` key further without specifying all 200 of them as a big list. There's an additional restriction applied in `include_globs` so that the script only runs on "https://www.google.*/*", but the addon store UI can't tell you that.

**Comment by wong2** [comment]
Thanks @marauder37 that's right

**Comment by chapmanjacobd** [comment]
It's working now. I wonder if Mozilla flagged it temporarily ? I don't know

**Comment by nkstnkst** [comment]
> It's not possible to limit the manifest matches key further without specifying all 200 of them as a big list. 
Still, it's probably worth it to explicitly list them, so people have ease of mind. It may be true that there is restriction applied in `include_globs` but I won't be notified if that changes. For me personally, I won't be using this given the aggressive access requirement.

**Comment by wong2** [comment]
@nkstnkst Thanks, I'll figure this out.

**Comment by gerardbosch** [comment]
Hi there, I see the issue is closed, but I'd like to give my 2 cents too on this topic @wong2 

I would also like to give support to the idea of "Principle of Least Privilege" if that's possible. If the problem is explicitly listing 200 domains, this looks quite feasible as it is a quite static content, so not many updates will be required in the future. If the problem is another thing (I'm not sure at all), it would be very nice of try addressing it with a more fine grained permission control.

When a user (including myself) faces this prompt, they think twice if go ahead or not:

![image](https://user-images.githubusercontent.com/30733556/206862130-0b664bc7-ffcc-4b68-be93-0bb2cad422e6.png)

The fact that the project is Open Source gives an extra point of confidence, but still not everyone will have the time or knowledge to validate it.

I hope this feedback can help in any sense :)

Cheers!

Relates to: https://github.com/wong2/chat-gpt-google-extension/issues/35#issuecomment-1339408344, https://github.com/wong2/chat-gpt-google-extension/issues/35

**Comment by gerardbosch** [comment]
Ooops! I've just seen this was somehow addressed recently here https://github.com/wong2/chat-gpt-google-extension/commit/ce17eeb248e058361abca2d9fd972454ce62731d

But I've just tried to install the extension from Chrome Web Store and the "Read and change all your data on all websites" was requested.

**Comment by wong2** [comment]
@gerardbosch yeah resolved in v1.3.0 still pending for review in Web store

**Comment by gerardbosch** [comment]
> @gerardbosch yeah resolved in v1.3.0 still pending for review in Web store

Awesome! Thanks so much for answering :smiley:
