### ISSUE TITLE
Unnecessary permission required to access data of all website

### ISSUE THREAD

**Issue by gzqx** [wong2/chat-gpt-google-extension#73]
On Firefox, the add-on requires accessing data of all website, which I don't think is necessary.

**Comment by wong2** [comment]
Fixed https://github.com/wong2/chat-gpt-google-extension/commit/ce17eeb248e058361abca2d9fd972454ce62731d

**Comment by gerardbosch** [comment]
Hi @wong2 I like what you fixed here regarding permissions 👏: https://github.com/wong2/chat-gpt-google-extension/commit/ce17eeb248e058361abca2d9fd972454ce62731d

I'm just wondering if would make sense to replace these kind of lines: https://github.com/wong2/chat-gpt-google-extension/blob/1c96266d087b8aed69fad088bc908442a27db158/src/manifest.json#L23 with something like the following (search queries seem to be requested on `www` subdomain):

```
"https://www.google.com/search*",
```

**Rationale:**

This is because in this case (Google) you send the login request through `https://accounts.google.com` which matches `*.google.com`. I guess (not sure) that as the trailing path `/search*` will not match, the accounts subdomain will never be "intercepted" by the extension?

But the thing is that the message that is presented to the user is "All google.com sites" (see screenshot). So I was thinking if the UX can be improved by restricting to something like `www.google.com` or at least making it more obvious when you look at the manifest code.

What do you think?

![image](https://user-images.githubusercontent.com/30733556/208087160-fd5a77e1-6418-42b9-90b0-ff8eac93cfb0.png)

**Comment by wong2** [comment]
@gerardbosch that makes sense! i will change it

**Comment by wong2** [comment]
Fixed https://github.com/wong2/chat-gpt-google-extension/commit/38e456f2ed8eb4089c80f81c2a929aa5e87bdd1f

**Comment by gerardbosch** [comment]
:heart:
