### ISSUE TITLE
low quality results filter

### ISSUE THREAD

**Issue by chapmanjacobd** [wong2/chat-gpt-google-extension#78]
It would be nice if there was an option to disable showing the ChatGPT response if it contains the text "training only goes up until 2021", "not able to browse the internet", "I am a large language model trained by OpenAI", "Can you please provide more information or clarify your question?", or "Could you please provide more context or information?"

**Comment by jt-wang** [comment]
Though they are of low quality, they are a good indication to users to refresh the page.

**Comment by chapmanjacobd** [comment]
If ChatGPT can provide better responses with re-requests (I don't believe this is true), shouldn't those refreshes be automated ? 

Why do humans need to be stuck in the loop. "robots in the loop, humans in the group"

**Comment by jt-wang** [comment]
That's a great point Jacob! On the second thought, the difference between this extension and ChatGPT itself is that, this extension isn't designed to keep the conversation session, while ChatGPT does. 

With this premise, when this extension receives a low-quality response from ChatGPT, though it can either hide it, or refresh the page, it still bumps into problems below：

1. **hide it**: if the response is simply hidden, user would be confused - what happened out there?
                if the response is replaced with a sentence "response is hidden because it's of low quality" - it doesn't make much difference with showing the original response, at least the original carry context to let users know what caused the low-quality response.

2. **refresh the page**: because the low-quality result often is due to the nature of the question itself, refresh doesn't really solve it.

**Comment by leahein** [comment]
I think the idea would be that with option 1, it would be a setting for the user to disable. So if they have the setting to hide low quality results enabled, and don't see anything, they would know why, which shouldn't lead to a confusing UX.

I could see this being helpful, since often those results are just noise.
